# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text="see: <a href=''></a>", max_length=5, verbose_name='Kind of annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text="see: <a href='http://hdl.handle.net/11459/CCR_C-2520_9eeedfb4-47d3-ddee-cfcb-99ac634bf1db'>description</a>", verbose_name='Describes the collection as a whole')),
            ],
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('dutch_name', models.CharField(max_length=50)),
                ('machine_value', models.IntegerField(help_text='The actual numeric value stored in the database. Created automatically.')),
            ],
            options={
                'ordering': ['field', 'machine_value'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text="see: <a href='http://hdl.handle.net/11459/CCR_C-2956_519a4aab-2f76-0fd3-090e-f0d6b81a7dbb'>legalOwner</a>", verbose_name='One of the collection or resource owners')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text="see: <a href='http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#type'>Dublin type</a>", max_length=5, verbose_name='Type of this resource')),
                ('annotation', models.ManyToManyField(to='collection.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text="see: <a href='http://hdl.handle.net/11459/CCR_C-2544_3626545e-a21d-058c-ebfd-241c0464e7e5'>resourceName</a>", verbose_name='Title used for the collection as a whole')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ManyToManyField(to='collection.Owner'),
        ),
        migrations.AddField(
            model_name='collection',
            name='resource',
            field=models.ManyToManyField(to='collection.Resource'),
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.ManyToManyField(to='collection.Title'),
        ),
    ]
