# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationtype',
            name='format',
            field=models.CharField(choices=[('1', 'manual'), ('5', 'none'), ('4', 'other'), ('2', 'readme file'), ('3', 'website')], default='0', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-5434_9c284553-b24c-d3ea-f3e8-5bebf0ee5f44'>Documentation: type</a>", max_length=5, verbose_name='Kind of documentation'),
        ),
    ]
