# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160617_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(default='0', help_text='Sorry, no help available for resource.media.format', max_length=5, verbose_name='Media format')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='format',
            field=models.CharField(default='0', help_text='Sorry, no help available for resource.annotation.format', max_length=5, verbose_name='Annotation format'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='mode',
            field=models.CharField(default='0', help_text='Sorry, no help available for resource.annotation.mode', max_length=5, verbose_name='Annotation mode'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='type',
            field=models.CharField(default='0', help_text='Sorry, no help available for resource.annotation.type', max_length=5, verbose_name='Kind of annotation'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2520_9eeedfb4-47d3-ddee-cfcb-99ac634bf1db'>Description of the collection</a>", verbose_name='Describes the collection as a whole'),
        ),
        migrations.AlterField(
            model_name='helpchoice',
            name='help_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.TextField(help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2956_519a4aab-2f76-0fd3-090e-f0d6b81a7dbb'>One of the owners of the collection</a>", verbose_name='One of the collection or resource owners'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(help_text="See: <a href='http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#type'>Type of this resource (Dublin Core)</a>", max_length=5, verbose_name='Type of this resource'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2544_3626545e-a21d-058c-ebfd-241c0464e7e5'>A title of the collection</a>", verbose_name='Title used for the collection as a whole'),
        ),
    ]
