# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160711_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(default='-', help_text="See: <a href='http://purl.org/dc/terms/relation'>Relation</a>", max_length=80, verbose_name='Relation with something else'),
        ),
    ]
