# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160617_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for speechcorpus.channel', max_length=5, verbose_name='Channel for the speech corpus')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterEncoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for writtencorpus.characterencoding.name', max_length=5, verbose_name='Domain')),
            ],
        ),
        migrations.CreateModel(
            name='ConversantionalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for speechcorpus.conversationaltype', max_length=5, verbose_name='Type of conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for domain.name', max_length=5, verbose_name='Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for genre.name', max_length=5, verbose_name='Collection genre')),
            ],
        ),
        migrations.CreateModel(
            name='GeographicProvenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='0', help_text='Sorry, no help available for provenance.geographic.country', max_length=5, verbose_name='Country included in this geographic coverage')),
                ('place', models.CharField(blank=True, help_text='Sorry, no help available for provenance.geographic.place', max_length=80, verbose_name='Place (city) included in this coverage')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for language.name', max_length=5, verbose_name='Language in collection')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageDisorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for languagedisorder.name', max_length=5, verbose_name='Language disorder')),
            ],
        ),
        migrations.CreateModel(
            name='Linguality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LingualityAgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for linguality.lingualityagegroup', max_length=5, verbose_name='Age group of linguality')),
            ],
        ),
        migrations.CreateModel(
            name='LingualityNativeness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for linguality.lingualitynativeness', max_length=5, verbose_name='Nativeness type of linguality')),
            ],
        ),
        migrations.CreateModel(
            name='LingualityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for linguality.lingualitystatus', max_length=5, verbose_name='Status of linguality')),
            ],
        ),
        migrations.CreateModel(
            name='LingualityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for linguality.lingualitytype', max_length=5, verbose_name='Type of linguality')),
            ],
        ),
        migrations.CreateModel(
            name='LingualityVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for linguality.lingualityvariant', max_length=5, verbose_name='Variant of linguality')),
            ],
        ),
        migrations.CreateModel(
            name='MultilingualityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for linguality.multilingualitytype', max_length=5, verbose_name='Type of multi-linguality')),
            ],
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geographicProvenance', models.ManyToManyField(blank=True, to='collection.GeographicProvenance')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for speechcorpus.recordingenvironment', max_length=5, verbose_name='Environment for the recording')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', help_text='Sorry, no help available for relation.name', max_length=5, verbose_name='Relation with something else')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Channel')),
                ('conversationalType', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.ConversantionalType')),
                ('recordingEnvironment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.RecordingEnvironment')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalProvenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startYear', models.IntegerField(default=2016, verbose_name='First year covered by the collection')),
                ('endYear', models.IntegerField(default=2016, verbose_name='Last year covered by the collection')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterEncoding', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.CharacterEncoding')),
            ],
        ),
        migrations.AlterField(
            model_name='annotation',
            name='format',
            field=models.CharField(default='0', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2562_872eb94a-47fb-b551-2f64-13ded063259e'>Format of this annotation layer</a>", max_length=5, verbose_name='Annotation format'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='mode',
            field=models.CharField(default='0', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2506_48f68696-57f3-74da-38e8-aa0f8e6ecc2f'>Annotation mode</a>", max_length=5, verbose_name='Annotation mode'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ManyToManyField(blank=True, to='collection.Owner'),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.CharField(default='0', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2571_2be2e583-e5af-34c2-3673-93359ec1f7df'>Format of this resource medium</a>", max_length=5, verbose_name='Media format'),
        ),
        migrations.AddField(
            model_name='provenance',
            name='temporalProvenance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.TemporalProvenance'),
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityAgeGroup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.LingualityAgeGroup'),
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityNativeness',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.LingualityNativeness'),
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityStatus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.LingualityStatus'),
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.LingualityType'),
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityVariant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.LingualityVariant'),
        ),
        migrations.AddField(
            model_name='linguality',
            name='multilingualityType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.MultilingualityType'),
        ),
        migrations.AddField(
            model_name='collection',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Genre'),
        ),
        migrations.AddField(
            model_name='collection',
            name='language',
            field=models.ManyToManyField(to='collection.Language'),
        ),
        migrations.AddField(
            model_name='collection',
            name='languageDisorder',
            field=models.ManyToManyField(blank=True, to='collection.LanguageDisorder'),
        ),
        migrations.AddField(
            model_name='collection',
            name='linguality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Linguality'),
        ),
        migrations.AddField(
            model_name='collection',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Provenance'),
        ),
        migrations.AddField(
            model_name='collection',
            name='relation',
            field=models.ManyToManyField(blank=True, to='collection.Relation'),
        ),
        migrations.AddField(
            model_name='collection',
            name='speechCorpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.SpeechCorpus'),
        ),
        migrations.AddField(
            model_name='collection',
            name='writtenCorpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.WrittenCorpus'),
        ),
    ]
