# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160714_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='format',
            field=models.CharField(choices=[('33', 'AIF'), ('34', 'BAS'), ('35', 'MT'), ('36', 'TRS'), ('1', 'application/json'), ('2', 'application/pdf'), ('37', 'other'), ('3', 'text/html'), ('4', 'text/plain'), ('5', 'text/plain-bas'), ('6', 'text/praat-textgrid'), ('21', 'text/x-cgn-bpt+xml'), ('22', 'text/x-cgn-lxk+xml'), ('23', 'text/x-cgn-pri+xml'), ('24', 'text/x-cgn-prx+xml'), ('25', 'text/x-cgn-skp+xml'), ('26', 'text/x-cgn-tag+xml'), ('27', 'text/x-cgn-tig+xml'), ('8', 'text/x-chat'), ('9', 'text/x-cut'), ('10', 'text/x-eaf+xml'), ('11', 'text/x-esf'), ('38', 'text/x-folia+xml'), ('29', 'text/x-jasmin-awd+text'), ('31', 'text/x-jasmin-hmi+text'), ('28', 'text/x-jasmin-ort+text'), ('30', 'text/x-jasmin-pos+text'), ('12', 'text/x-lexus-config+xml'), ('13', 'text/x-lexus-resource+xml'), ('14', 'text/x-lmf+xml'), ('32', 'text/x-mmax+xml'), ('15', 'text/x-shoebox-language'), ('18', 'text/x-shoebox-lexicon'), ('16', 'text/x-shoebox-text'), ('17', 'text/x-shoebox-type'), ('20', 'text/x-toolbox-lexicon'), ('19', 'text/x-toolbox-text'), ('7', 'text/xml')], default='0', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2562_872eb94a-47fb-b551-2f64-13ded063259e'>Format of this annotation layer</a>", max_length=5, verbose_name='Annotation format'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('2', 'alignment'), ('3', 'audienceReactions'), ('4', 'bodyMovements'), ('8', 'discourseAnnotation'), ('7', 'discourseAnnotation-dialogueActs'), ('55', 'discourseAnnotation-other'), ('9', 'discourseAnnotation-relations'), ('10', 'discourseAnnotation-textualEntailment'), ('54', 'events'), ('11', 'facialExpressions'), ('12', 'gazeEyeMovements'), ('13', 'glosses'), ('14', 'handArmGestures'), ('15', 'handManipulationOfObjects'), ('16', 'headMovements'), ('17', 'lemmatization'), ('18', 'links'), ('19', 'lipMovements'), ('1', 'noAnnotation'), ('21', 'orthographicTranscription'), ('52', 'other'), ('23', 'phoneticTranscription'), ('24', 'polarity'), ('25', 'posTagging'), ('26', 'prompts'), ('27', 'prosodicAnnotation'), ('28', 'questionTopicalTarget'), ('29', 'segmentation'), ('30', 'semanticAnnotation'), ('31', 'semanticAnnotation-classes'), ('56', 'semanticAnnotation-coreference'), ('20', 'semanticAnnotation-namedEntities'), ('57', 'semanticAnnotation-other'), ('32', 'semanticAnnotation-relations'), ('33', 'semanticAnnotation-roles'), ('46', 'semanticAnnotation-temporalExpressions'), ('51', 'semanticAnnotation-wordSenses'), ('34', 'sentiment'), ('37', 'soundEvents'), ('38', 'soundToTextAlignment'), ('39', 'speakerIdentification'), ('40', 'speakerTurns'), ('41', 'speechActs'), ('42', 'speechAnnotation'), ('43', 'stemming'), ('44', 'structuralAnnotation'), ('45', 'subcategorizationFrames'), ('53', 'syntacticAnnotation'), ('58', 'syntacticAnnotation-other'), ('36', 'syntacticAnnotation-shallowParsing'), ('50', 'syntacticAnnotation-treebanks'), ('47', 'textualEntailment'), ('48', 'translation'), ('49', 'transliteration')], default='0', max_length=5, verbose_name='Kind of annotation'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('20', 'academic-nonfiction'), ('2', 'conversation'), ('22', 'fiction'), ('4', 'interviews'), ('19', 'lectures'), ('7', 'newspaper-article'), ('21', 'non-academic-non-fiction'), ('17', 'other'), ('24', 'personal-notes'), ('11', 'prompted speech'), ('12', 'radio/TV-broadcast'), ('25', 'social-media-texts'), ('15', 'speeches'), ('23', 'stimuli'), ('26', 'test-scores'), ('18', 'unknown')], default='0', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2470_d191f2b2-6339-f031-b534-70d526b28357'>Genre of the collection as a whole</a>", max_length=5, verbose_name='Collection genre'),
        ),
        migrations.AlterField(
            model_name='mediaformat',
            name='name',
            field=models.CharField(choices=[('3', 'audio/x-aiff'), ('4', 'audio/x-mp2'), ('5', 'audio/x-mp3'), ('6', 'audio/x-mpeg4'), ('7', 'audio/x-wav'), ('11', 'image/gif'), ('8', 'image/jpeg'), ('9', 'image/png'), ('10', 'image/tiff'), ('20', 'other'), ('14', 'text/folia'), ('12', 'text/html'), ('1', 'text/pdf'), ('13', 'text/tei'), ('2', 'text/xml'), ('21', 'unknown'), ('18', 'video/quicktime'), ('15', 'video/x-mpeg1'), ('16', 'video/x-mpeg2'), ('17', 'video/x-mpeg4'), ('19', 'video/x-msvideo')], default='0', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2571_2be2e583-e5af-34c2-3673-93359ec1f7df'>Format of this resource medium</a>", max_length=5, verbose_name='Format of a medium'),
        ),
    ]
