# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20160617_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterencoding',
            name='name',
            field=models.CharField(default='0', help_text='Sorry, no help available for characterencoding.name', max_length=5, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='0', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2470_d191f2b2-6339-f031-b534-70d526b28357'>Genre of the collection as a whole</a>", max_length=5, verbose_name='Collection genre'),
        ),
    ]
