# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20160618_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='genre',
        ),
        migrations.AddField(
            model_name='collection',
            name='genre',
            field=models.ManyToManyField(blank=True, to='collection.Genre'),
        ),
        migrations.RemoveField(
            model_name='linguality',
            name='lingualityAgeGroup',
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityAgeGroup',
            field=models.ManyToManyField(blank=True, to='collection.LingualityAgeGroup'),
        ),
        migrations.RemoveField(
            model_name='linguality',
            name='lingualityNativeness',
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityNativeness',
            field=models.ManyToManyField(blank=True, to='collection.LingualityNativeness'),
        ),
        migrations.RemoveField(
            model_name='linguality',
            name='lingualityStatus',
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityStatus',
            field=models.ManyToManyField(blank=True, to='collection.LingualityStatus'),
        ),
        migrations.RemoveField(
            model_name='linguality',
            name='lingualityType',
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityType',
            field=models.ManyToManyField(blank=True, to='collection.LingualityType'),
        ),
        migrations.RemoveField(
            model_name='linguality',
            name='lingualityVariant',
        ),
        migrations.AddField(
            model_name='linguality',
            name='lingualityVariant',
            field=models.ManyToManyField(blank=True, to='collection.LingualityVariant'),
        ),
        migrations.RemoveField(
            model_name='linguality',
            name='multilingualityType',
        ),
        migrations.AddField(
            model_name='linguality',
            name='multilingualityType',
            field=models.ManyToManyField(blank=True, to='collection.MultilingualityType'),
        ),
    ]
