# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20160618_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpchoice',
            name='searchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='format',
            field=models.CharField(choices=[('33', 'AIF'), ('34', 'BAS'), ('35', 'MT'), ('36', 'TRS'), ('1', 'application/json'), ('2', 'application/pdf'), ('37', 'other'), ('3', 'text/html'), ('4', 'text/plain'), ('5', 'text/plain-bas'), ('6', 'text/praat-textgrid'), ('21', 'text/x-cgn-bpt+xml'), ('22', 'text/x-cgn-lxk+xml'), ('23', 'text/x-cgn-pri+xml'), ('24', 'text/x-cgn-prx+xml'), ('25', 'text/x-cgn-skp+xml'), ('26', 'text/x-cgn-tag+xml'), ('27', 'text/x-cgn-tig+xml'), ('8', 'text/x-chat'), ('9', 'text/x-cut'), ('10', 'text/x-eaf+xml'), ('11', 'text/x-esf'), ('29', 'text/x-jasmin-awd+text'), ('31', 'text/x-jasmin-hmi+text'), ('28', 'text/x-jasmin-ort+text'), ('30', 'text/x-jasmin-pos+text'), ('12', 'text/x-lexus-config+xml'), ('13', 'text/x-lexus-resource+xml'), ('14', 'text/x-lmf+xml'), ('32', 'text/x-mmax+xml'), ('15', 'text/x-shoebox-language'), ('18', 'text/x-shoebox-lexicon'), ('16', 'text/x-shoebox-text'), ('17', 'text/x-shoebox-type'), ('20', 'text/x-toolbox-lexicon'), ('19', 'text/x-toolbox-text'), ('7', 'text/xml')], default='0', help_text='Sorry, no help available for resource.annotation.format', max_length=5, verbose_name='Annotation format'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='mode',
            field=models.CharField(choices=[('1', 'automatic'), ('4', 'interactive'), ('2', 'manual'), ('3', 'mixed'), ('5', 'other'), ('6', 'unknown')], default='0', help_text='Sorry, no help available for resource.annotation.mode', max_length=5, verbose_name='Annotation mode'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text='Sorry, no help available for description', verbose_name='Describes the collection as a whole'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('1', 'biography'), ('2', 'conversation'), ('3', 'drama'), ('4', 'interviews'), ('5', 'legal-texts'), ('6', 'medical-texts'), ('7', 'newspaper-article'), ('8', 'novel'), ('17', 'other'), ('9', 'personal-notes'), ('10', 'poetry'), ('11', 'prompted speech'), ('12', 'radio/TV-broadcast'), ('13', 'ritual/religious texts'), ('14', 'secondary-document'), ('15', 'speeches'), ('16', 'stimuli'), ('18', 'unknown')], default='0', help_text='Sorry, no help available for genre.name', max_length=5, verbose_name='Collection genre'),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.CharField(choices=[('2', 'CDROM'), ('3', 'DVD'), ('1', 'application/pdf'), ('2', 'application/smil+xml'), ('3', 'audio/x-aiff'), ('4', 'audio/x-mp2'), ('5', 'audio/x-mp3'), ('6', 'audio/x-mpeg4'), ('7', 'audio/x-wav'), ('4', 'blueray'), ('5', 'hard disk'), ('11', 'image/gif'), ('8', 'image/jpeg'), ('9', 'image/png'), ('10', 'image/tiff'), ('1', 'internet'), ('7', 'other'), ('20', 'other'), ('6', 'paper copy'), ('14', 'text/folia'), ('12', 'text/html'), ('13', 'text/tei'), ('21', 'unknown'), ('8', 'video'), ('18', 'video/quicktime'), ('15', 'video/x-mpeg1'), ('16', 'video/x-mpeg2'), ('17', 'video/x-mpeg4'), ('19', 'video/x-msvideo')], default='0', help_text='Sorry, no help available for resource.media.format', max_length=5, verbose_name='Media format'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for owner', verbose_name='One of the collection or resource owners'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('13', 'Dataset:frequencylist-POStags'), ('11', 'Dataset:frequencylist-lemmas'), ('14', 'Dataset:frequencylist-ngrams'), ('17', 'Dataset:frequencylist-other'), ('15', 'Dataset:frequencylist-phrasetypes'), ('16', 'Dataset:frequencylist-sentencetypes'), ('12', 'Dataset:frequencylist-wordtypes'), ('3', 'Dataset:lexicon'), ('6', 'Dataset:list-POStags'), ('4', 'Dataset:list-lemmas'), ('7', 'Dataset:list-ngrams'), ('10', 'Dataset:list-other'), ('8', 'Dataset:list-phrasetypes'), ('9', 'Dataset:list-sentencetypes'), ('5', 'Dataset:list-wordtypes'), ('2', 'Dataset:table'), ('1', 'Dataset:treebank'), ('24', 'Image:moving-animation'), ('25', 'Image:moving-film'), ('26', 'Image:moving-other'), ('22', 'Image:still-drawing'), ('19', 'Image:still-graph'), ('18', 'Image:still-map'), ('23', 'Image:still-other'), ('21', 'Image:still-photo'), ('20', 'Image:still-picture'), ('27', 'InteractiveResource'), ('33', 'Other'), ('30', 'Sound:music'), ('31', 'Sound:other'), ('29', 'Sound:songs'), ('28', 'Sound:speech'), ('32', 'Text')], help_text='Sorry, no help available for resource.type', max_length=5, verbose_name='Type of this resource'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for title', verbose_name='Title used for the collection as a whole'),
        ),
    ]
