# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20160629_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='nonCommercialUsageOnly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.NonCommercialUsageOnly'),
        ),
    ]
