# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20160704_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='ISBN',
            field=models.TextField(blank=True, help_text='Sorry, no help available for access.ISBN', verbose_name='ISBN of collection'),
        ),
        migrations.AlterField(
            model_name='access',
            name='ISLRN',
            field=models.TextField(blank=True, help_text='Sorry, no help available for access.ISLRN', verbose_name='ISLRN of collection'),
        ),
        migrations.AlterField(
            model_name='accessavailability',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for access.availability', max_length=5, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='accesscontact',
            name='address',
            field=models.TextField(help_text='Sorry, no help available for access.contact.address', verbose_name='Access: address of contact'),
        ),
        migrations.AlterField(
            model_name='accesscontact',
            name='email',
            field=models.EmailField(help_text='Sorry, no help available for access.contact.email', max_length=254, verbose_name='Access: email of contact'),
        ),
        migrations.AlterField(
            model_name='accesscontact',
            name='person',
            field=models.TextField(help_text='Sorry, no help available for access.contact.person', verbose_name='Access: person to contact'),
        ),
        migrations.AlterField(
            model_name='accessmedium',
            name='format',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for access.medium.format', max_length=5, verbose_name='Resource medium'),
        ),
        migrations.AlterField(
            model_name='accesswebsite',
            name='name',
            field=models.URLField(help_text='Sorry, no help available for access.website', verbose_name='Website to access the collection'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='format',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for resource.annotation.format', max_length=5, verbose_name='Annotation format'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='mode',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for resource.annotation.mode', max_length=5, verbose_name='Annotation mode'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for resource.annotation.type', max_length=5, verbose_name='Kind of annotation'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for speechcorpus.audience.type', max_length=5, verbose_name='Audience'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for speechcorpus.channel', max_length=5, verbose_name='Channel for the speech corpus'),
        ),
        migrations.AlterField(
            model_name='characterencoding',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for writtencorpus.characterencoding.name', max_length=5, verbose_name='Character encoding'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='clarinCentre',
            field=models.TextField(blank=True, help_text='Sorry, no help available for clarincentre.name', verbose_name='Clarin centre in charge'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text='Sorry, no help available for description', verbose_name='Describes the collection as a whole'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='version',
            field=models.TextField(blank=True, help_text='Sorry, no help available for version', verbose_name='Version of the collection'),
        ),
        migrations.AlterField(
            model_name='conversationaltype',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for speechcorpus.conversationaltype', max_length=5, verbose_name='Type of conversation'),
        ),
        migrations.AlterField(
            model_name='documentationfile',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for documentation.file', verbose_name='File name for documentation'),
        ),
        migrations.AlterField(
            model_name='documentationtype',
            name='format',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for documentation.type', max_length=5, verbose_name='RKind of documentation'),
        ),
        migrations.AlterField(
            model_name='documentationurl',
            name='name',
            field=models.URLField(help_text='Sorry, no help available for documentation.url', verbose_name='URL of documentation'),
        ),
        migrations.AlterField(
            model_name='domaindescription',
            name='name',
            field=models.TextField(default='0', help_text='Sorry, no help available for domain.name', verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for genre.name', max_length=5, verbose_name='Collection genre'),
        ),
        migrations.AlterField(
            model_name='geographicprovenance',
            name='country',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for country.name', max_length=5, verbose_name='Country included in this geographic coverage'),
        ),
        migrations.AlterField(
            model_name='interactivity',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for speechcorpus.interactivity.name', max_length=5, verbose_name='Interactivity'),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for speechcorpus.involvement.name', max_length=5, verbose_name='Type of involvement'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for language.name', max_length=5, verbose_name='Language in collection'),
        ),
        migrations.AlterField(
            model_name='languagedisorder',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for languagedisorder.name', max_length=5, verbose_name='Language disorder'),
        ),
        migrations.AlterField(
            model_name='licensename',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for access.licenseName', verbose_name='Name of the license'),
        ),
        migrations.AlterField(
            model_name='licenseurl',
            name='name',
            field=models.URLField(help_text='Sorry, no help available for access.licenseURL', verbose_name='URL of the license'),
        ),
        migrations.AlterField(
            model_name='lingualityagegroup',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for linguality.lingualityagegroup', max_length=5, verbose_name='Age group of linguality'),
        ),
        migrations.AlterField(
            model_name='lingualitynativeness',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for linguality.lingualitynativeness', max_length=5, verbose_name='Nativeness type of linguality'),
        ),
        migrations.AlterField(
            model_name='lingualitystatus',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for linguality.lingualitystatus', max_length=5, verbose_name='Status of linguality'),
        ),
        migrations.AlterField(
            model_name='lingualitytype',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for linguality.lingualitytype', max_length=5, verbose_name='Type of linguality'),
        ),
        migrations.AlterField(
            model_name='lingualityvariant',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for linguality.lingualityvariant', max_length=5, verbose_name='Variant of linguality'),
        ),
        migrations.AlterField(
            model_name='mediaformat',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for resource.media.format', max_length=5, verbose_name='Format of a medium'),
        ),
        migrations.AlterField(
            model_name='multilingualitytype',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for linguality.multilingualitytype', max_length=5, verbose_name='Type of multi-linguality'),
        ),
        migrations.AlterField(
            model_name='noncommercialusageonly',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for access.nonCommercialUsageOnly', max_length=5, verbose_name='Non-commercial usage only access'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for resourceCreator.organization', verbose_name='Name of organization'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for owner', verbose_name='One of the collection or resource owners'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for resourceCreator.person', verbose_name='Name of person'),
        ),
        migrations.AlterField(
            model_name='pid',
            name='code',
            field=models.TextField(help_text='Sorry, no help available for PID', verbose_name='Persistent identifier of the collection'),
        ),
        migrations.AlterField(
            model_name='planningtype',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for speechcorpus.planningtype.name', max_length=5, verbose_name='Type of planning'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(help_text='Sorry, no help available for project.title', verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='projectfunder',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for project.funder', verbose_name='Funder of project'),
        ),
        migrations.AlterField(
            model_name='projecturl',
            name='name',
            field=models.URLField(help_text='Sorry, no help available for project.url', verbose_name='URL of project'),
        ),
        migrations.AlterField(
            model_name='recordingcondition',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for speechcorpus.recordingConditions', verbose_name='Recording condition'),
        ),
        migrations.AlterField(
            model_name='recordingenvironment',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for speechcorpus.recordingenvironment', max_length=5, verbose_name='Environment for the recording'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for relation.name', max_length=5, verbose_name='Relation with something else'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for resource.type', max_length=5, verbose_name='Type of this resource'),
        ),
        migrations.AlterField(
            model_name='socialcontext',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for speechcorpus.socialcontext.name', max_length=5, verbose_name='Social context'),
        ),
        migrations.AlterField(
            model_name='speechcorpus',
            name='durationOfEffectiveSpeech',
            field=models.TextField(blank=True, default='0', help_text='Sorry, no help available for speechcorpus.durationOfEffectiveSpeech', verbose_name='Duration of effective speech'),
        ),
        migrations.AlterField(
            model_name='speechcorpus',
            name='durationOfFullDatabase',
            field=models.TextField(blank=True, default='0', help_text='Sorry, no help available for speechcorpus.durationOfFullDatabase', verbose_name='Duration of full database'),
        ),
        migrations.AlterField(
            model_name='speechcorpus',
            name='numberOfSpeakers',
            field=models.IntegerField(blank=True, default=0, help_text='Sorry, no help available for speechcorpus.numberOfSpeakers', verbose_name='Number of speakers'),
        ),
        migrations.AlterField(
            model_name='speechcorpus',
            name='speakerDemographics',
            field=models.TextField(blank=True, default='-', help_text='Sorry, no help available for speechcorpus.speakerDemographics', verbose_name='Speaker demographics'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(help_text='Sorry, no help available for title', verbose_name='Title used for the collection as a whole'),
        ),
        migrations.AlterField(
            model_name='totalsize',
            name='sizeUnit',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for totalSize.sizeUnit', max_length=5, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='validationmethod',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for validation.method', max_length=5, verbose_name='Validation method'),
        ),
        migrations.AlterField(
            model_name='validationtype',
            name='name',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for validation.type', max_length=5, verbose_name='Validation type'),
        ),
    ]
