# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_auto_20160706_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalsize',
            name='sizeUnit',
            field=models.CharField(default='MB', help_text="See: <a href='http://hdl.handle.net/11459/CCR_C-2583_5f5cb491-1037-8d46-d685-ccebfc0233f7'>Units used for the amount</a>", max_length=50, verbose_name='Units'),
        ),
    ]
