# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_collection_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description of this resource'),
        ),
    ]
