# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='totalSize',
            field=models.ManyToManyField(blank=True, to='collection.TotalSize'),
        ),
    ]
